resources:
- name: gpos_src
  type: git
  source:
    uri: git@github.com:greenplum-db/gpos.git
    branch: master
    private_key: {{private_key}}

jobs:
- name: gpos
  plan:
    - get: gpos_src
      trigger: true
    - aggregate:
      - task: build_debug_centos5
        file: gpos_src/concourse/build_debug_centos5.yml
      - task: build_release_centos5
        file: gpos_src/concourse/build_release_centos5.yml
