resources:
- name: gpos_src
  type: git
  source:
    uri: git@github.com:greenplum-db/gpos.git
    branch: master
    private_key: {{private_key}}
- name: xerces_patch
  type: git
  source:
    uri: git@github.com:Pivotal-DataFabric/orca-concourse-temp
    branch: master
    private_key: {{private_key}}
    paths:
    - optimizer/patches/xerces-c-gpdb.patch
    - optimizer/concourse/xerces-c

jobs:
- name: gpos
  plan:
    - get: gpos_src
      trigger: true
    - task: build_centos5_debug
      file: gpos_src/concourse/build_debug_centos5.yml
- name: gp_xerces
  plan:
    - get: xerces_patch
      trigger: true
    - task: build_centos5_debug
      file: xerces_patch/optimizer/concourse/xerces-c/build_xerces_centos5.yml
