resources:
# Input source repos.
- name: gpos_src
  type: git
  source:
    uri: git@github.com:greenplum-db/gpos.git
    branch: master
    private_key: {{private_key}}
- name: xerces_patch
  type: git
  source:
    uri: git@github.com:Pivotal-DataFabric/orca-concourse-temp
    branch: master
    private_key: {{private_key}}
    paths:
    - optimizer/patches/xerces-c-gpdb.patch
    - optimizer/concourse/xerces-c
    - optimizer/concourse/package_tarball.bash
- name: orca_src
  type: git
  source:
    uri: git@github.com:Pivotal-DataFabric/orca-concourse-temp
    branch: master
    private_key: {{private_key}}
# Patched Xerces-C binaries.
- name: bin_xerces_centos5
  type: s3
  source:
    region_name: us-west-2
    bucket: gpdb-concourse
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}
    versioned_file: bin_xerces_centos5.tar.gz
- name: bin_xerces_debian8
  type: s3
  source:
    region_name: us-west-2
    bucket: gpdb-concourse
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}
    versioned_file: bin_xerces_debian8.tar.gz
# GPOS binaries.
- name: bin_gpos_centos5_debug
  type: s3
  source:
    region_name: us-west-2
    bucket: gpdb-concourse
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}
    versioned_file: bin_gpos_centos5_debug.tar.gz
- name: bin_gpos_centos5_release
  type: s3
  source:
    region_name: us-west-2
    bucket: gpdb-concourse
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}
    versioned_file: bin_gpos_centos5_release.tar.gz
- name: bin_gpos_debian8_debug
  type: s3
  source:
    region_name: us-west-2
    bucket: gpdb-concourse
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}
    versioned_file: bin_gpos_debian8_debug.tar.gz
- name: bin_gpos_debian8_release
  type: s3
  source:
    region_name: us-west-2
    bucket: gpdb-concourse
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}
    versioned_file: bin_gpos_debian8_release.tar.gz
# Orca binaries.
- name: bin_orca_centos5_debug
  type: s3
  source:
    region_name: us-west-2
    bucket: gpdb-concourse
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}
    versioned_file: bin_orca_centos5_debug.tar.gz
- name: bin_orca_centos5_release
  type: s3
  source:
    region_name: us-west-2
    bucket: gpdb-concourse
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}
    versioned_file: bin_orca_centos5_release.tar.gz
- name: bin_orca_debian8_debug
  type: s3
  source:
    region_name: us-west-2
    bucket: gpdb-concourse
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}
    versioned_file: bin_orca_debian8_debug.tar.gz
- name: bin_orca_debian8_release
  type: s3
  source:
    region_name: us-west-2
    bucket: gpdb-concourse
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}
    versioned_file: bin_orca_debian8_release.tar.gz

jobs:
- name: gpos
  plan:
    - get: gpos_src
      trigger: true
    # Build matrix for GPOS.
    - aggregate:
      - task: build_and_test_centos5_debug
        file: gpos_src/concourse/build_centos5_debug.yml
      - task: build_and_test_centos5_release
        file: gpos_src/concourse/build_centos5_release.yml
      - task: build_and_test_debian8_debug
        file: gpos_src/concourse/build_debian8_debug.yml
      - task: build_and_test_debian8_release
        file: gpos_src/concourse/build_debian8_release.yml
    # Package binary tarballs and upload to S3 when all builds and tests succeed.
    - aggregate:
      - task: package_tarball_centos5_debug
        file: gpos_src/concourse/package_tarball_centos5_debug.yml
      - task: package_tarball_centos5_release
        file: gpos_src/concourse/package_tarball_centos5_release.yml
      - task: package_tarball_debian8_debug
        file: gpos_src/concourse/package_tarball_debian8_debug.yml
      - task: package_tarball_debian8_release
        file: gpos_src/concourse/package_tarball_debian8_release.yml
    - aggregate:
      - put: bin_gpos_centos5_debug
        params:
          from: package_tarball_centos5_debug/bin_gpos_centos5_debug.tar.gz
      - put: bin_gpos_centos5_release
        params:
          from: package_tarball_centos5_release/bin_gpos_centos5_release.tar.gz
      - put: bin_gpos_debian8_debug
        params:
          from: package_tarball_debian8_debug/bin_gpos_debian8_debug.tar.gz
      - put: bin_gpos_debian8_release
        params:
          from: package_tarball_debian8_release/bin_gpos_debian8_release.tar.gz
- name: gp_xerces
  plan:
    - get: xerces_patch
      trigger: true
    # Build matrix for Xerces.
    - aggregate:
      - task: build_centos5
        file: xerces_patch/optimizer/concourse/xerces-c/build_xerces_centos5.yml
      - task: build_debian8
        file: xerces_patch/optimizer/concourse/xerces-c/build_xerces_debian8.yml
    # Package binary tarballs and upload to S3 when all builds succeed.
    - aggregate:
      - task: package_tarball_centos5
        file: xerces_patch/optimizer/concourse/xerces-c/package_tarball_centos5.yml
      - task: package_tarball_debian8
        file: xerces_patch/optimizer/concourse/xerces-c/package_tarball_debian8.yml
    - aggregate:
      - put: bin_xerces_centos5
        params:
          from: package_tarball_centos5/bin_xerces_centos5.tar.gz
      - put: bin_xerces_debian8
        params:
          from: package_tarball_debian8/bin_xerces_debian8.tar.gz
- name: orca
  plan:
    # Get dependencies.
    - aggregate:
      - get: bin_gpos_centos5_debug
        trigger: true
        passed:
        - gpos
      - get: bin_gpos_centos5_release
        trigger: true
        passed:
        - gpos
      - get: bin_gpos_debian8_debug
        trigger: true
        passed:
        - gpos
      - get: bin_gpos_debian8_release
        trigger: true
        passed:
        - gpos
      - get: bin_xerces_centos5
        trigger: true
        passed:
        - gp_xerces
      - get: bin_xerces_debian8
        trigger: true
        passed:
        - gp_xerces
      - get: orca_src
        trigger: true
    # Build matrix for Orca.
    - aggregate:
      - task: build_and_test_centos5_debug
        file: orca_src/optimizer/concourse/build_and_test_centos5_debug.yml
      - task: build_and_test_centos5_release
        file: orca_src/optimizer/concourse/build_and_test_centos5_release.yml
      - task: build_and_test_debian8_debug
        file: orca_src/optimizer/concourse/build_and_test_debian8_debug.yml
      - task: build_and_test_debian8_release
        file: orca_src/optimizer/concourse/build_and_test_debian8_release.yml
    # Package binary tarballs and upload to S3 when all builds and tests succeed.
    - aggregate:
      - task: package_tarball_centos5_debug
        file: orca_src/optimizer/concourse/package_tarball_centos5_debug.yml
      - task: package_tarball_centos5_release
        file: orca_src/optimizer/concourse/package_tarball_centos5_release.yml
      - task: package_tarball_debian8_debug
        file: orca_src/optimizer/concourse/package_tarball_debian8_debug.yml
      - task: package_tarball_debian8_release
        file: orca_src/optimizer/concourse/package_tarball_debian8_release.yml
    - aggregate:
      - put: bin_orca_centos5_debug
        params:
          from: package_tarball_centos5_debug/bin_orca_centos5_debug.tar.gz
      - put: bin_orca_centos5_release
        params:
          from: package_tarball_centos5_release/bin_orca_centos5_release.tar.gz
      - put: bin_orca_debian8_debug
        params:
          from: package_tarball_debian8_debug/bin_orca_debian8_debug.tar.gz
      - put: bin_orca_debian8_release
        params:
          from: package_tarball_debian8_release/bin_orca_debian8_release.tar.gz

