resources:
- name: gpos_src
  type: git
  source:
    uri: git@github.com:greenplum-db/gpos.git
    branch: master
    private_key: {{private_key}}
- name: xerces_patch
  type: git
  source:
    uri: git@github.com:Pivotal-DataFabric/orca-concourse-temp
    branch: master
    private_key: {{private_key}}
    paths:
    - optimizer/patches/xerces-c-gpdb.patch
    - optimizer/concourse/xerces-c
- name: orca_src
  type: git
  source:
    uri: git@github.com:Pivotal-DataFabric/orca-concourse-temp
    branch: master
    private_key: {{private_key}}
- name: bin_xerces_centos5
  type: s3
  source:
    region_name: us-west-2
    bucket: gpdb-concourse
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}
    versioned_file: bin_xerces_centos5.tar.gz
- name: bin_gpos_centos5_debug
  type: s3
  source:
    region_name: us-west-2
    bucket: gpdb-concourse
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}
    versioned_file: bin_gpos_centos5_debug.tar.gz

jobs:
- name: gpos
  plan:
    - get: gpos_src
      trigger: true
    - task: build_and_test_centos5_debug
      file: gpos_src/concourse/build_centos5_debug.yml
    - task: package_tarball_centos5_debug
      file: gpos_src/concourse/package_tarball_centos5_debug.yml
    - put: bin_gpos_centos5_debug
      params:
        from: package_tarball_centos5_debug/bin_gpos_centos5_debug.tar.gz
- name: gp_xerces
  plan:
    - get: xerces_patch
      trigger: true
    - task: build_centos5
      file: xerces_patch/optimizer/concourse/xerces-c/build_xerces_centos5.yml
- name: orca
  plan:
    - aggregate:
      - get: bin_gpos_centos5_debug
        trigger: true
        passed:
        - gpos
      - get: orca_src
        trigger: true
